all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
- - 20
all_joints_names:
- bodypart1
- bodypart2
- bodypart3
- bodypart4
- bodypart5
- bodypart6
- bodypart7
- bodypart8
- bodypart9
- bodypart10
- bodypart11
- bodypart12
- bodypart13
- bodypart14
- bodypart15
- bodypart16
- bodypart17
- bodypart18
- bodypart19
- bodypart20
- bodypart21
alpha_r: 0.02
apply_prob: 0.5
batch_size: 8
clahe: true
claheratio: 0.1
crop_sampling: hybrid
crop_size:
- 400
- 400
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_PkPvRnetYu00Jul20/PkPvRnetYu00_Yuna90shuffle1.pickle
dataset_type: multi-animal-imgaug
decay_steps: 30000
display_iters: 500
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: true
histeqratio: 0.1
init_weights: /home/xp2027/.local/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/mobilenet_v2_1.0_224.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_PkPvRnetYu00Jul20/Documentation_data-PkPvRnetYu00_90shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.0001
  - 7500
- - 5.0e-05
  - 12000
- - 1.0e-05
  - 200000
net_type: mobilenet_v2_1.0
num_idchannel: 0
num_joints: 21
num_limbs: 63
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- - 7
  - 16
- - 5
  - 7
- - 7
  - 9
- - 7
  - 19
- - 7
  - 18
- - 2
  - 7
- - 7
  - 17
- - 16
  - 17
- - 3
  - 16
- - 1
  - 16
- - 16
  - 19
- - 10
  - 16
- - 13
  - 16
- - 4
  - 17
- - 17
  - 18
- - 1
  - 17
- - 17
  - 19
- - 15
  - 17
- - 14
  - 17
- - 11
  - 17
- - 5
  - 18
- - 1
  - 5
- - 5
  - 12
- - 5
  - 9
- - 5
  - 14
- - 3
  - 5
- - 4
  - 8
- - 4
  - 9
- - 3
  - 4
- - 10
  - 18
- - 10
  - 15
- - 0
  - 10
- - 6
  - 10
- - 10
  - 13
- - 2
  - 18
- - 6
  - 18
- - 0
  - 18
- - 2
  - 12
- - 2
  - 6
- - 2
  - 9
- - 2
  - 13
- - 12
  - 20
- - 12
  - 15
- - 6
  - 12
- - 12
  - 13
- - 0
  - 12
- - 12
  - 19
- - 12
  - 14
- - 1
  - 9
- - 9
  - 14
- - 3
  - 20
- - 3
  - 15
- - 6
  - 20
- - 19
  - 20
- - 1
  - 8
- - 8
  - 19
- - 15
  - 19
- - 14
  - 15
- - 0
  - 1
- - 6
  - 13
- - 0
  - 11
- - 11
  - 14
- - 14
  - 19
partaffinityfield_predict: true
pos_dist_thresh: 17
pre_resize: []
project_path: /scratch/xp2027/lab_36_PkPvRnetYu/PkPvRnetYu00
rotation: 25
rotratio: 0.4
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
weigh_only_present_joints: false
