all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
all_joints_names:
- bodypart1
- bodypart2
- bodypart3
- bodypart4
- bodypart5
- bodypart6
- bodypart7
- bodypart8
- bodypart9
- bodypart10
- bodypart11
- bodypart12
alpha_r: 0.02
apply_prob: 0.5
batch_size: 8
clahe: true
claheratio: 0.1
crop_sampling: hybrid
crop_size:
- 400
- 400
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_OrSsEnetXi01Jul10/OrSsEnetXi01_Xiaojia95shuffle0.pickle
dataset_type: multi-animal-imgaug
decay_steps: 30000
display_iters: 500
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: true
histeqratio: 0.1
init_weights: /home/xp2027/.local/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_OrSsEnetXi01Jul10/Documentation_data-OrSsEnetXi01_95shuffle0.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.0001
  - 7500
- - 5.0e-05
  - 12000
- - 1.0e-05
  - 200000
net_type: resnet_50
num_idchannel: 0
num_joints: 12
num_limbs: 66
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- - 0
  - 1
- - 0
  - 2
- - 0
  - 3
- - 0
  - 4
- - 0
  - 5
- - 0
  - 6
- - 0
  - 7
- - 0
  - 8
- - 0
  - 9
- - 0
  - 10
- - 0
  - 11
- - 1
  - 2
- - 1
  - 3
- - 1
  - 4
- - 1
  - 5
- - 1
  - 6
- - 1
  - 7
- - 1
  - 8
- - 1
  - 9
- - 1
  - 10
- - 1
  - 11
- - 2
  - 3
- - 2
  - 4
- - 2
  - 5
- - 2
  - 6
- - 2
  - 7
- - 2
  - 8
- - 2
  - 9
- - 2
  - 10
- - 2
  - 11
- - 3
  - 4
- - 3
  - 5
- - 3
  - 6
- - 3
  - 7
- - 3
  - 8
- - 3
  - 9
- - 3
  - 10
- - 3
  - 11
- - 4
  - 5
- - 4
  - 6
- - 4
  - 7
- - 4
  - 8
- - 4
  - 9
- - 4
  - 10
- - 4
  - 11
- - 5
  - 6
- - 5
  - 7
- - 5
  - 8
- - 5
  - 9
- - 5
  - 10
- - 5
  - 11
- - 6
  - 7
- - 6
  - 8
- - 6
  - 9
- - 6
  - 10
- - 6
  - 11
- - 7
  - 8
- - 7
  - 9
- - 7
  - 10
- - 7
  - 11
- - 8
  - 9
- - 8
  - 10
- - 8
  - 11
- - 9
  - 10
- - 9
  - 11
- - 10
  - 11
partaffinityfield_predict: true
pos_dist_thresh: 17
pre_resize: []
project_path: /scratch/xp2027/lab_33_OrSSRnetXi/OrSsRnetXi
rotation: 25
rotratio: 0.4
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
weigh_only_present_joints: false
